id: IC432C6FF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T16:21:09+00:00'
last_modified: '2022-06-07T13:40:22.440434+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22086
  title: འདུལ་ཊཱིཀ་རིན་ཆེན་འཕྲེང་བ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    1E2C:
      image_group_id: I1PD36397
      title: ''
      total_pages: 646
      order: 1
      base_file: 1E2C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
