id: P000768
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W22086
  title: འདུལ་ཊཱིཀ་རིན་ཆེན་འཕྲེང་བ
  author: ''
  volumes:
    1781efa8825f49d389e1735be187da9f:
      image_group_id: I1PD36397
      title: ''
      volume_number: 1
      total_pages: 646
      base_file: v001.txt
